import source from "../../../data/catalog.json";
import type { Tool, Plan, Rule, Registry, Connection } from "./types";
import { templates } from "../stack/templates";
// Capability assignments describe the catalog's product scope; all remain researched.
const categories: Record<string, string[]> = {
  "App builders": ["customer_interface"],
  "Websites and content": ["website"],
  "Data and backend": ["database"],
  "Workflow automation": ["workflow_automation"],
  "Identity and membership": ["authentication", "customer_accounts"],
  "Payments and billing": ["payments"],
  "Commerce and marketplaces": [
    "product_catalog",
    "online_ordering",
    "order_management",
  ],
  "Customer relationship management": ["crm"],
  "Accounting and inventory": ["accounting", "invoicing"],
  "Booking and events": ["booking"],
  "Forms and intake": ["forms"],
  "Email marketing": ["email_marketing"],
  "Messaging and collaboration": [],
  "Transactional messages and notifications": ["transactional_email"],
  "Customer support": ["customer_support"],
  "AI models and agent builders": ["ai_agent"],
  "Voice AI and retrieval": [],
  "Analytics and reporting": ["analytics"],
  "Files media and signatures": ["file_storage"],
  "Shipping maps and delivery": [],
  "Internal app builders": ["owner_dashboard"],
  "Work and project management": ["project_management"],
  "Hosting and deployment": ["hosting"],
  "Monitoring and reliability": ["monitoring"],
  "People and HR operations": ["hr"],
  "Embedded integration platforms": ["embedded_integrations"],
};
const capabilities: Record<string, string[]> = {
  bubble: [
    "customer_interface",
    "database",
    "authentication",
    "customer_accounts",
    "workflow_automation",
  ],
  softr: ["customer_interface", "customer_accounts"],
  glide: ["customer_interface", "owner_dashboard"],
  weweb: ["customer_interface"],
  flutterflow: ["customer_interface", "mobile_app"],
  adalo: ["customer_interface", "mobile_app", "database", "customer_accounts"],
  wix: [
    "website",
    "customer_interface",
    "product_catalog",
    "online_ordering",
    "order_management",
    "booking",
    "crm",
    "owner_dashboard",
  ],
  contentful: ["product_catalog"],
  sanity: ["product_catalog"],
  airtable: ["database", "forms", "owner_dashboard"],
  supabase: ["database", "backend", "authentication", "file_storage"],
  xano: ["database", "backend", "authentication"],
  firebase: [
    "database",
    "backend",
    "authentication",
    "hosting",
    "notifications",
  ],
  stripe: ["payments", "subscriptions", "invoicing", "marketplace_payments"],
  paypal: ["payments", "subscriptions", "invoicing"],
  square: ["payments", "product_catalog", "inventory", "owner_dashboard"],
  paddle: ["payments", "subscriptions"],
  "lemon-squeezy": ["payments", "subscriptions"],
  chargebee: ["subscriptions"],
  outseta: ["authentication", "customer_accounts", "subscriptions", "crm"],
  shopify: [
    "customer_interface",
    "product_catalog",
    "online_ordering",
    "order_management",
    "customer_accounts",
    "owner_dashboard",
  ],
  woocommerce: [
    "product_catalog",
    "online_ordering",
    "order_management",
    "subscriptions",
  ],
  bigcommerce: [
    "customer_interface",
    "product_catalog",
    "online_ordering",
    "order_management",
  ],
  ecwid: [
    "customer_interface",
    "product_catalog",
    "online_ordering",
    "order_management",
  ],
  sharetribe: [
    "customer_interface",
    "product_catalog",
    "customer_accounts",
    "booking",
    "order_management",
    "owner_dashboard",
  ],
  snipcart: ["online_ordering", "payments"],
  odoo: ["accounting", "inventory", "invoicing"],
  "zoho-inventory": ["inventory"],
  "google-calendar": ["calendar"],
  twilio: ["sms", "voice", "whatsapp"],
  "whatsapp-business-platform": ["whatsapp"],
  vonage: ["sms", "voice"],
  zoom: ["voice"],
  onesignal: ["notifications"],
  novu: ["notifications"],
  dify: ["ai_agent", "knowledge_retrieval"],
  voiceflow: ["ai_agent", "knowledge_retrieval", "customer_interface"],
  botpress: ["ai_agent", "knowledge_retrieval", "customer_interface"],
  vapi: ["voice", "ai_agent"],
  "retell-ai": ["voice", "ai_agent"],
  elevenlabs: ["voice"],
  pinecone: ["knowledge_retrieval"],
  qdrant: ["knowledge_retrieval"],
  algolia: ["knowledge_retrieval"],
  docusign: ["electronic_signature"],
  pandadoc: ["electronic_signature"],
  shippo: ["shipping"],
  shipstation: ["shipping"],
  easypost: ["shipping"],
  "google-maps-platform": [],
  mapbox: [],
  onfleet: ["delivery"],
  appsheet: ["owner_dashboard", "customer_interface"],
  budibase: ["owner_dashboard", "database"],
  noloco: ["owner_dashboard", "customer_interface"],
};
// Only reviewed, unambiguous formulas are executable. Every original price remains available.
type Entry = [
  string,
  number | null,
  Plan["billing_period"],
  string?,
  string?,
  Rule[]?,
];
const fixed: Record<string, Entry> = {
  bubble: ["Web and Mobile Starter", 59, "annual"],
  flutterflow: ["Basic", 39, "unknown"],
  adalo: ["Starter", 36, "annual"],
  supabase: ["Pro", 25, "monthly"],
  xano: ["Essential", 85, "annual"],
  make: ["Core", 9, "annual"],
  zapier: ["Professional", 19.99, "annual"],
  activepieces: ["Plus", 16, "annual"],
  clerk: ["Pro", 20, "annual"],
  bigcommerce: ["Core", 29, "annual"],
  sharetribe: ["Lite", 99, "annual"],
  "quickbooks-online": ["Simple Start", 38, "monthly", "USD", "US"],
  xero: ["Early", 25, "monthly", "USD", "US"],
  "zoho-books": ["Standard", 20, "monthly", "USD", "US"],
  resend: ["Pro", 20, "monthly"],
  postmark: ["Basic", 15, "monthly"],
  mailgun: ["Basic", 15, "monthly"],
  onfleet: ["Launch", 619, "monthly"],
  pinecone: ["Builder", 20, "monthly"],
  n8n: ["Cloud Starter", 20, "annual", "EUR"],
  apideck: ["Launch", 599, "monthly", "GBP"],
  shopify: ["Basic (India observation)", 1499, "annual", "INR", "IN"],
  airtable: [
    "Team",
    0,
    "annual",
    "USD",
    undefined,
    [
      {
        formula: "per_seat",
        metric: "employees",
        unit_price: 20,
        threshold: 0,
        bucket: "fixed",
      },
    ],
  ],
  stripe: [
    "US domestic cards",
    0,
    "usage",
    "USD",
    "US",
    [
      {
        formula: "percentage",
        metric: "revenue",
        unit_price: 0.029,
        threshold: 0,
        bucket: "transaction",
        country: "US",
      },
      {
        formula: "per_transaction",
        metric: "monthly_transactions",
        unit_price: 0.3,
        threshold: 0,
        bucket: "transaction",
        country: "US",
      },
    ],
  ],
  paypal: [
    "US PayPal Checkout",
    0,
    "usage",
    "USD",
    "US",
    [
      {
        formula: "percentage",
        metric: "revenue",
        unit_price: 0.0349,
        threshold: 0,
        bucket: "transaction",
        country: "US",
      },
      {
        formula: "per_transaction",
        metric: "monthly_transactions",
        unit_price: 0.49,
        threshold: 0,
        bucket: "transaction",
        country: "US",
      },
    ],
  ],
  paddle: [
    "Standard",
    0,
    "usage",
    "USD",
    undefined,
    [
      {
        formula: "percentage",
        metric: "revenue",
        unit_price: 0.05,
        threshold: 0,
        bucket: "transaction",
      },
      {
        formula: "per_transaction",
        metric: "monthly_transactions",
        unit_price: 0.5,
        threshold: 0,
        bucket: "transaction",
      },
    ],
  ],
  vapi: [
    "Hosting",
    0,
    "usage",
    "USD",
    undefined,
    [
      {
        formula: "per_minute",
        metric: "monthly_minutes",
        unit_price: 0.05,
        threshold: 0,
        bucket: "variable",
      },
    ],
  ],
  "retell-ai": [
    "Voice",
    0,
    "usage",
    "USD",
    undefined,
    [
      {
        formula: "per_minute",
        metric: "monthly_minutes",
        unit_price: 0.07,
        max_unit_price: 0.31,
        threshold: 0,
        bucket: "variable",
      },
    ],
  ],
  snipcart: [
    "Platform",
    0,
    "usage",
    "USD",
    undefined,
    [
      {
        formula: "minimum",
        metric: "revenue",
        unit_price: 0.02,
        threshold: 20,
        bucket: "variable",
      },
    ],
  ],
};
export function catalogRegistry(): Registry {
  const tools: Tool[] = source.tools.map((r) => {
    const entry = fixed[r.slug];
    const plan: Plan = {
      id: r.slug + "-catalog",
      tool_id: r.slug,
      name: entry?.[0] ?? "Plan requires confirmation",
      currency: entry?.[3] ?? "USD",
      billing_period: entry?.[2] ?? "unknown",
      base_price: entry?.[1] ?? null,
      pricing_type: entry?.[5]?.length
        ? "metered"
        : entry
          ? "subscription"
          : "unknown",
      included_units: {},
      plan_requirements: r.constraints,
      price_status: entry
        ? "observed"
        : /quote|sales|custom pricing/i.test(r.price_text)
          ? "custom_quote"
          : "requires_confirmation",
      price_text: r.price_text,
      rules: entry?.[5] ?? [],
      country: entry?.[4] ?? null,
      production_eligible: null,
      complete_price: false,
    };
    if (r.slug === "onfleet") plan.included_units.monthly_delivery_tasks = 2500;
    if (r.slug === "make") plan.included_units.monthly_workflow_credits = 10000;
    if (r.slug === "postmark") {
      plan.included_units.monthly_messages = 10000;
      plan.rules = [
        {
          formula: "per_message",
          metric: "monthly_messages",
          unit_price: 0.0018,
          threshold: 10000,
          bucket: "variable",
          note: "Displayed starting overage",
        },
      ];
    }
    const self = /self-host/.test(r.description + " " + r.price_text);
    return {
      id: r.slug,
      slug: r.slug,
      name: r.name,
      vendor: r.name,
      description: r.description,
      category: r.category,
      website_url: r.references[0] ?? null,
      logo_url: null,
      hosted_or_self_hosted: self ? "both" : "unknown",
      integration_route: r.integration_route,
      status: "discovery",
      capabilities: capabilities[r.slug] ?? categories[r.category] ?? [],
      readiness: "RESEARCHED",
      constraints: r.constraints,
      integration_setup: r.integration_setup,
      source_reference: source.source.id + ":" + r.catalog_number,
      references: r.references,
      last_researched: r.last_researched,
      regions: [],
      limits: [{ metric: "unconfirmed", value: null, notes: r.constraints }],
      api_support: null,
      webhook_support: null,
      business_models: ["paddle", "lemon-squeezy"].includes(r.slug)
        ? ["digital", "saas"]
        : [],
      plans: [plan],
    };
  });
  // These exact named pairs appear in catalog product setup or example stacks.
  const pairs: [string, string, string][] = [
    ["softr", "airtable", "Softr integration setup explicitly names Airtable"],
    ["weweb", "xano", "WeWeb integration setup explicitly names Xano"],
    ["weweb", "supabase", "WeWeb integration setup explicitly names Supabase"],
    [
      "flutterflow",
      "supabase",
      "FlutterFlow description explicitly names Supabase",
    ],
    [
      "flutterflow",
      "firebase",
      "FlutterFlow description explicitly names Firebase",
    ],
    [
      "memberstack",
      "stripe",
      "Memberstack integration setup explicitly names Stripe",
    ],
    ["outseta", "stripe", "Outseta integration setup explicitly names Stripe"],
    [
      "wix",
      "stripe",
      "Service business example: supported Stripe or other Wix payment connection",
    ],
    [
      "sharetribe",
      "stripe",
      "Marketplace example: Sharetribe-supported Stripe marketplace payment setup",
    ],
    ["shopify", "shippo", "Online store example shipping role"],
    ["shopify", "shipstation", "Online store example shipping role"],
    ["shopify", "quickbooks-online", "Online store example owner operations"],
    ["adalo", "xano", "Delivery example customer interface and backend"],
    ["xano", "onfleet", "Delivery example backend callbacks and dispatch"],
    [
      "voiceflow",
      "xano",
      "AI support example authenticated business action endpoints",
    ],
    ["appsheet", "google-sheets", "Internal operations example record source"],
  ];
  const connections: Connection[] = pairs.map(([a, b, n]) => ({
    id: a + "--" + b,
    tool_a_id: a,
    tool_b_id: b,
    connection_type: ["weweb", "flutterflow"].includes(a)
      ? "configured_api"
      : "unknown",
    middleware_tool_id: null,
    verified: false,
    readiness_status: "RESEARCHED",
    setup_complexity: null,
    supported_direction: "unknown",
    notes:
      n +
      ". Proposed route; exact plan, operation, and transport require verification.",
    last_verified_at: null,
    source_reference: source.source.id,
    authentication_method: null,
    required_scopes: null,
    webhook_support: null,
    polling_support: null,
    rate_limits: null,
    retry_behavior: null,
    idempotency_support: null,
    known_constraints: [
      "Not tested end to end",
      "Required plans and operations unconfirmed",
    ],
    operations: [],
    required_plan_ids: [],
  }));
  return {
    version: source.source.sha256,
    researched_at: source.source.researched_at,
    tools,
    connections,
    templates,
  };
}
