import type { Template } from "../registry/types";
const define = (
  id: string,
  name: string,
  types: string[],
  caps: string[],
  optional: string[],
  tools: string[],
): Template => ({
  template_id: id,
  name,
  business_types: types,
  default_capabilities: caps,
  optional_capabilities: optional,
  recommended_stack_pattern: tools,
  tested_connections: [],
  confidence: 0.7,
  readiness_status: "RESEARCHED",
});
export const templates: Template[] = [
  define(
    "cloud-kitchen",
    "Cloud kitchen",
    ["cloud kitchen", "restaurant", "food delivery"],
    [
      "customer_interface",
      "product_catalog",
      "online_ordering",
      "payments",
      "order_management",
      "owner_dashboard",
    ],
    ["delivery", "subscriptions", "multi_location", "accounting"],
    ["adalo", "xano", "stripe", "onfleet"],
  ),
  define(
    "online-store",
    "Online store",
    ["online store", "ecommerce", "e-commerce", "shop"],
    [
      "customer_interface",
      "product_catalog",
      "online_ordering",
      "payments",
      "order_management",
      "owner_dashboard",
    ],
    ["shipping", "inventory", "accounting"],
    ["shopify", "shippo", "quickbooks-online"],
  ),
  define(
    "service",
    "Service business",
    ["service business", "consulting", "salon", "cleaning"],
    ["website", "booking", "payments", "crm"],
    ["calendar", "invoicing"],
    ["wix", "hubspot", "make"],
  ),
  define(
    "portal",
    "Client portal",
    ["client portal", "portal"],
    [
      "customer_interface",
      "customer_accounts",
      "database",
      "file_storage",
      "owner_dashboard",
    ],
    ["invoicing", "forms"],
    ["softr", "airtable", "stripe"],
  ),
  define(
    "marketplace",
    "Marketplace",
    ["marketplace", "two-sided"],
    [
      "customer_interface",
      "product_catalog",
      "customer_accounts",
      "marketplace_payments",
      "order_management",
      "owner_dashboard",
    ],
    ["booking", "notifications"],
    ["sharetribe", "stripe"],
  ),
  define(
    "saas",
    "Subscription software",
    ["saas", "software subscription"],
    [
      "customer_interface",
      "authentication",
      "database",
      "subscriptions",
      "owner_dashboard",
    ],
    ["organizations", "analytics"],
    ["bubble", "stripe"],
  ),
  define(
    "ai-support",
    "AI support app",
    ["ai support", "customer support app", "support application"],
    [
      "customer_interface",
      "ai_agent",
      "knowledge_retrieval",
      "customer_support",
    ],
    ["database", "analytics"],
    ["voiceflow", "xano", "zendesk"],
  ),
  define(
    "receptionist",
    "AI receptionist",
    ["ai receptionist", "voice agent"],
    ["voice", "ai_agent", "booking", "crm"],
    ["calendar", "sms"],
    ["retell-ai", "cal-com", "hubspot"],
  ),
  define(
    "internal",
    "Internal operations",
    ["internal operations", "internal app"],
    ["owner_dashboard", "database", "workflow_automation"],
    ["inventory", "forms"],
    ["appsheet", "google-sheets", "make"],
  ),
];
